---
  - name: Make sure httplib2 is installed
    pip: name=httplib2

  - name: Get salt values
    uri: url=https://api.wordpress.org/secret-key/1.1/salt/ return_content=yes
    register: wp_salt

  - name: Set salts
    set_fact:
      salts: "{{ wp_salt.content }}"

  - name: Make sure data directory exists
    file: path={{ work_dir }}/data/{{ site_name }} state=directory

  - name: Get wordpress
    get_url: url=https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz dest={{ work_dir }}/wordpress.tar.gz

  - name: Unarchive wordpress
    unarchive: src={{ work_dir }}/wordpress.tar.gz dest={{ work_dir }}/data/{{ site_name }} copy=no

  - name: Remove wordpress zip
    file: path={{ work_dir }}/wordpress.tar.gz state=absent

  - name: Create a wp-config
    template: src=wp-config.j2 dest={{ work_dir }}/data/{{ site_name }}/wordpress/wp-config.php

  - name: Set permissions
    file: path={{ work_dir }}/data/{{ site_name }}/wordpress/wp-content state=directory mode=0775 owner=www-data recurse=yes
