---
  - name: Make sure data directory exists
    file: path={{ work_dir }}/data/{{ site_name }} state=directory

  - name: Move MySQL backup over
    unarchive: src=./backups/wp_backup.sql.tar.gz dest={{ work_dir }}

  - name: Unarchive wordpress
    unarchive: src=./backups/site_backup.tar.gz dest={{ work_dir }}/data/{{ site_name }}
